# WaMDaM Docs config file
# Adel Abdallah, Utah State University
# Jan. 2018


# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.


# Repository
repo_name: WaMDaM-software-ecosystem
repo_url: https://github.com/WamdamProject/WaMDaM-software-ecosystem
edit_uri: "https://github.com/WamdamProject/WaMDaM-software-ecosystem/tree/master/mkdocs/Edit_MD_Files"

# Copyright
copyright: 'Copyright &copy; 2018 Adel M. Abdallah'

# Project information
site_name: WaMDaM Docs
docs_dir: Edit_MD_Files
site_description: Documentation of the Water Management Data Model (WaMDaM)
site_author: Adel M. Abdallah
site_url: http://docs.wamdam.org
site_dir: docs


# Page tree
pages:
  - Home: index.md
  - Why WaMDaM?: Why_WaMDaM.md
  - Rationale: Rationale.md
  - Authors: Authors.md  
  - Publications: Publications.md 
  - Open Source: OpenSource.md
  - Limitations: Limitations.md
  - Sponsors and Credit: SponsorsCredit.md
  - License: License.md
  - Get Started:
    - Steps: GetStarted/Steps.md
    - Prepare Data: GetStarted/PrepareData.md 
    - Use Wizard: GetStarted/Use_Wizard.md
    - Compare Scenarios: GetStarted/CompareScenarios.md  
    - Best Practices: GetStarted/Best_practices.md
    - Use Controlled Vocabularies: GetStarted/Use_controlled_vocabularies.md
  - Query & Select:
    - Use Cases: QuerySelect/UseCases.md
    - Use case 1: QuerySelect/use_case_1.md
    - Use case 2: QuerySelect/use_case_2.md
    - Use case 3: QuerySelect/use_case_3.md
    - Use case 4: QuerySelect/use_case_4.md
  - Serve to Models: 
    - Use Cases: ServeToModels/UseCases.md
    - WEAP: ServeToModels/WEAP.md 
    - WASH: ServeToModels/WASH.md 
  - Visualize & Publish: 
    - Use Cases: VisualizePublish/UseCases.md 
    - OpenAgua: VisualizePublish/OpenAgua.md
    - HydroShare: VisualizePublish/HydroShare.md
    - WEAP: VisualizePublish/WEAP.md
  - Documentation: 
    - Design Requirment: DesignDocumentation/Desing_Req.md
    - Design Approach: DesignDocumentation/DesignApproach.md
    - Information Model: DesignDocumentation/info_model.md
    - Logical Model Schema: DesignDocumentation/logical_Model.md
    - Physical Model Implementations: DesignDocumentation/Physical_Model.md
    - Controlled Vocabulary: DesignDocumentation/ControlledVocabulary.md
    - WaMDaM Wizard: DesignDocumentation/WaMDaM_Wizard.md
  - About: 
    - About: About.md    
# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/amabdallah
    - type: twitter
      link: https://twitter.com/adelmabdallah
    - type: linkedin
      link: https://linkedin.com/in/adelmabdallah/ 
# Configuration
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: Blue
    accent: indigo
# https://material.io/icons/
  logo:
    icon: home
  font:
    text: Roboto
    code: Roboto Mono
# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["UA-110152372-1"]
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
   
  
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  
